### ISSUE TITLE
Can't getResource

### ISSUE THREAD

**Issue by WarLock03** [documentnode/epub4j#5]
Resource resource = book.getResource(href);
	                         ^^^^^^^^^^^
The method getResource(String) is undefined for the type Book

How to get chapter content?

**Comment by jiakuan** [comment]
There is a method `getResources()` in `Book` class, which returns a `Resources` instance. Then you should be able to call `getByHref(href)` of the `resources` instance.

For example:

```
Resources resources = book.getResources();
Resource resource = resources.getByHref(href);
```
