### ISSUE TITLE
Cannot read epub

### ISSUE THREAD

**Issue by asm0dey** [documentnode/epub4j#7]
I have the following epub (renamed to zip to be able to attach to the GitHub issue):
[129374.zip](https://github.com/user-attachments/files/17994232/129374.zip)

It's being correctly opened by almost anything (my ebook, calibre, okular), but fails with obscure `net.sf.jazzlib.DataFormatException: Code lengths don't add up properly.` when I'm reading it with epub4j. 

The code hides stack trace, but in debugger, it looks like this:

```
0 = {StackTraceElement@14598} "net.sf.jazzlib.InflaterHuffmanTree.buildTree(InflaterHuffmanTree.java:110)"
1 = {StackTraceElement@14603} "net.sf.jazzlib.InflaterHuffmanTree.<init>(InflaterHuffmanTree.java:84)"
2 = {StackTraceElement@14604} "net.sf.jazzlib.InflaterDynHeader.buildDistTree(InflaterDynHeader.java:193)"
3 = {StackTraceElement@14605} "net.sf.jazzlib.Inflater.decode(Inflater.java:696)"
4 = {StackTraceElement@14606} "net.sf.jazzlib.Inflater.inflate(Inflater.java:315)"
5 = {StackTraceElement@14607} "net.sf.jazzlib.InflaterInputStream.read(InflaterInputStream.java:208)"
6 = {StackTraceElement@14608} "net.sf.jazzlib.ZipInputStream.read(ZipInputStream.java:300)"
7 = {StackTraceElement@14609} "java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)"
8 = {StackTraceElement@14610} "io.documentnode.epub4j.util.IOUtil.copy(IOUtil.java:121)"
9 = {StackTraceElement@14611} "io.documentnode.epub4j.util.IOUtil.toByteArray(IOUtil.java:47)"
10 = {StackTraceElement@14612} "io.documentnode.epub4j.domain.Resource.<init>(Resource.java:103)"
11 = {StackTraceElement@14613} "io.documentnode.epub4j.util.ResourceUtil.createResource(ResourceUtil.java:65)"
12 = {StackTraceElement@14614} "io.documentnode.epub4j.epub.ResourcesLoader.loadResources(ResourcesLoader.java:125)"
13 = {StackTraceElement@14615} "io.documentnode.epub4j.epub.EpubReader.readEpub(EpubReader.java:73)"
14 = {StackTraceElement@14616} "io.documentnode.epub4j.epub.EpubReader.readEpub(EpubReader.java:53)"
15 = {StackTraceElement@14617} "io.documentnode.epub4j.epub.EpubReader.readEpub(EpubReader.java:33)"
```

I'm not sure what's happening, probably it is something with jazzlib? In this case https://github.com/srikanth-lingala/zip4j is also a pure java implementation of zip.

**Comment by asm0dey** [comment]
I performed a small experiment: forked epub4j and replaced jazzlib with zip4j and it works! But one test fails: 
`testLoadResources_ZipInputStream_WithInvalidFile` fails because when reading from an inputstream zip4j assumes that there is one file header and creates a null resource.

**Comment by asm0dey** [comment]
The amount of changes needed is, surprisingly, not that big: https://github.com/asm0dey/epub4j/commit/93c15b325099fb3a652d8ba5eca1096b915bd398

**Comment by jiakuan** [comment]
zip4j looks great.
Does the test failure still exist?
Would you like to create a pull request?
Thanks.

**Comment by asm0dey** [comment]
@jiakuan thank you, PR is open now, please review. Please pay attention to the test I changed, probably I should emulate a previous behavior: for example, throw `ZipException` if `Resources` is empty.

If you happen to have a set of example epubs I would love to test the new code on them too.

**Comment by jiakuan** [comment]
The PR looks great.
Have merged to main.

**Comment by asm0dey** [comment]
@jiakuan if it's good I'd be happy to see it merged - I could really use the new version :)

**Comment by asm0dey** [comment]
Please let me know when/if you release it!

**Comment by jiakuan** [comment]
I will release a new version for this fix soon.

**Comment by jiakuan** [comment]
The new version 4.2.2 has been released to maven central, which should be available in a few hours.
